version: '3.8'

services:
  rdb:
    image: mysql:8.0.33
    restart: on-failure
    volumes:
      - ./tmp/rdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
