apiVersion: v1
kind: Service

metadata:
  name: contest-svc
  labels:
    name: tiwoori
    service: lb
    domain: contest
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    name: tiwoori
    service: server
    domain: contest
  ports:
    - name: contest
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer