spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  jackson.property-naming-strategy: SNAKE_CASE

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace