spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=REQUIRED&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE}
      minimum-idle: ${DB_MIN_IDLE}
      idle-timeout: ${DB_IDLE_TIMEOUT}
      max-lifetime: ${DB_MAX_LIFETIME}
      connection-timeout: ${DB_CONNECTION_TIMEOUT}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql.init.mode: never
  jackson.property-naming-strategy: SNAKE_CASE
  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  tomcat:
    threads:
      max: ${TOMCAT_THREAD_MAX}
    accept-count: ${TOMCAT_ACCEPT_COUNT}
    max-connections: ${TOMCAT_MAX_CONNECTIONS}
