apiVersion: v1
kind: ConfigMap
metadata:
  name: score-configmap
  namespace: prod
  labels:
    name: tiwoori
    service: config
    domain: score
data:
  contest.url: "a090e4158056c43ddb7df7015837d374-0c9d78252e4b198d.elb.ap-northeast-2.amazonaws.co"
  contest.port: "8080"
  contest_id: "53a70353-1f96-4b39-84f9-22704218627f"